// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_kanaji_feedback from "./routes/api/kanaji/feedback.ts";
import * as $api_restore_tikim from "./routes/api/restore/tikim.ts";
import * as $api_tikim_id_ from "./routes/api/tikim/[id].ts";
import * as $doushi_policy from "./routes/doushi-policy.tsx";
import * as $getman_policy from "./routes/getman-policy.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $policies_icon_brew from "./routes/policies/icon-brew.tsx";
import * as $policies_kanaji from "./routes/policies/kanaji.tsx";
import * as $policies_keystaff from "./routes/policies/keystaff.tsx";
import * as $policies_tikim from "./routes/policies/tikim.tsx";
import * as $tikim_policy from "./routes/tikim-policy.tsx";
import * as $Counter from "./islands/Counter.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/kanaji/feedback.ts": $api_kanaji_feedback,
    "./routes/api/restore/tikim.ts": $api_restore_tikim,
    "./routes/api/tikim/[id].ts": $api_tikim_id_,
    "./routes/doushi-policy.tsx": $doushi_policy,
    "./routes/getman-policy.tsx": $getman_policy,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/policies/icon-brew.tsx": $policies_icon_brew,
    "./routes/policies/kanaji.tsx": $policies_kanaji,
    "./routes/policies/keystaff.tsx": $policies_keystaff,
    "./routes/policies/tikim.tsx": $policies_tikim,
    "./routes/tikim-policy.tsx": $tikim_policy,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
